stages:
- stage: Build
  jobs:
  - job: Build
    pool:
      name: Azure Pipelines
    steps:
    - script: 'npm i node-gyp'
      displayName: 'Install node-gyp'
    - task: NodeTool@0
      displayName: 'Use Node version'
      inputs:
        versionSpec: 12
        checkLatest: false
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.7'
      displayName: 'Use Python 3.7'
    - script: |
        npm install
        npm run build
      displayName: 'npm install and build'
    - task: ArchiveFiles@1
      displayName: 'Archive files '
      inputs:
        rootFolder: '$(System.DefaultWorkingDirectory)'
        includeRootFolder: false
    - task: CopyFiles@2
      displayName: 'Copy File to: ArtifactsToBePublished'
      inputs:
        SourceFolder: '$(Build.ArtifactStagingDirectory)'
        Contents: '$(Build.BuildId).zip'
        TargetFolder: '$(Build.ArtifactStagingDirectory)\ArtifactsToBePublished'
    - task: PublishBuildArtifacts@1
      displayName: 'Publish Artifact: drop'
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)\ArtifactsToBePublished'
- stage: Deploy
  jobs:
  - deployment: DeployWeb
    pool:
      name: Azure Pipelines
    environment: 'econext-dev'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: AzureRmWebAppDeployment@3
            displayName: 'Deploy Azure App Service'
            inputs:
              azureSubscription: 'econext - 1 - Azure'
              appType: applinux
              WebAppName: econext
              ImageSource: Builtin
              RuntimeStack: 'NODE|12-lts'
              StartupCommand: 'node server.js'
              ScriptType: 'Inline Script'
              InlineScript: 'npm rebuild node-sass'