export default [
  'home',
  'indicator',
  'population',
  'gross-product',
  'local-jobs',
  'value-of-building-approvals',
  'workers-field-of-qualification',
  'number-of-businesses-by-industry',
  'industry-sector-analysis',
  'employment-by-industry',
  'employment-by-industry-fte',
  'employment-census',
  'worker-productivity-by-industry',
  'value-add-by-industry',
];
