const parentPages = [
  'size',
  'indicator',
  'structure',
  'spatial-economy',
  'industry-focus',
  'journey-to-work',
  'workforce-profiles',
  'labour-force',
  'local-market',
  'housing-market',
  'tourism',
  'reports-root',
  'about-economy-parent',
  'explanatory-notes',
];

export default [
  ...parentPages,
  'home',
  'population',
  'gross-product',
  'local-jobs',
  'value-of-building-approvals',
  'workers-field-of-qualification',
  'number-of-businesses-by-industry',
  'employment-by-industry',
  'employment-by-industry-fte',
  'employment-census',
  'worker-productivity-by-industry',
  'value-add-by-industry',
  'output-by-industry',
  'local-sales-by-industry',
  'exports-by-industry',
  'imports-by-industry',
  'field-of-qualification',
  'industry',
  'age-structure',
  'hours-worked',
  'occupations',
  'qualifications',
  'labourforce-key-statistics',
  'income',
  'income-quartiles',
  'workers-age-structure',
  'workers-hours-worked',
  'workers-occupations',
  'workers-level-of-qualifications',
  'workers-income',
  'workers-income-quartile',
  'workers-travel-to-work',
  'travel-to-work',
  'about-economy-id',
  'industry-sector-definitions',
  'population-types',
  'data-sources',
  'gross-regional-product',
  'workers-key-statistics',
  'workers-key-statistics-lite',
  'labourforce-key-statistics',
  'labourforce-key-statistics-lite',
  'unemployed-keystats',
  'industry-sector-analysis',
  'site-map',
  'accessibility-economy',
  'economic-model-updates',
  'glossary',
  'topic-notes',
  'shift-share',
  'income-sources',
  'industry-composition',
  'household-expenditure',
  'unemployment',
  'Employment-capacity',
  'employed-residents',
  'retail-trade',
  'consumer-price-index',
  // 'tourism-visitor-summary',
  // 'tourism-visitors-nights',
  // 'tourism-visitors-reason',
  // 'tourism-value',
  // 'covid19',
];
